### ISSUE TITLE
uint64_t vs int64_t

### ISSUE THREAD

**Issue by AppuCodes** [Cubitect/cubiomes#121]
The examples in README.md use uint64_t, but they don't support negative values
I'm confused why they are used, because Minecraft worlds can also use negative seeds, so wouldn't it be ideal to replace them to just int64_t or long? (Sorry IDK that much C++)

**Comment by arnaud-ma** [comment]
The library seems to be made so that if you pass a seed (even negative), it is implicitly cast to uint64_t with the correct corresponding seed so you don't have to worry about that (as long as your base seed is between -2^63 and 2^63 - 1). 

If on the other hand you have an uint64 seed and you want the int64 one, you can cast the value explicitly (see https://www.w3schools.com/c/c_type_conversion.php)

**Comment by Cubitect** [comment]
Signed integer arithmetic is undefined behavior in C when the result overflows, while unsigned arithmetic always uses twos-complement, which is what we need to simulate Java's behavior. Hence uint64_t instead of int64_t. The value can always be cast to int64_t when a signed representation is needed (this simply reinterprets the most significant bit as the sign-bit).

At the start of the project I actually used `long` as the integer type for seeds, which has the additional problems that the size it undefined. In particular, it turns out that Windows uses 32-bit integers for `long`.
