### ISSUE TITLE
pthread.h missing for compiling?

### ISSUE THREAD

**Issue by Zodsmar** [Cubitect/cubiomes#14]
Hello I am trying to get this to compile and I get this as an error:

make
gcc -c -Wall -fwrapv -march=native -O3 find_quadhuts.c
In file included from find_quadhuts.c:9:0:
finders.h:7:21: fatal error: pthread.h: No such file or directory
 #include <pthread.h>
                     ^
compilation terminated.
makefile:23: recipe for target 'find_quadhuts.o' failed
make: *** [find_quadhuts.o] Error 1

(Also I would love a more detailed explanation of how to make this work!) It seems way faster and more efficient for searching for seeds than what I am building... if your curious: https://github.com/Zodsmar/SeedSearcherStandaloneTool

Thanks!

**Comment by Zodsmar** [comment]
So I guess trying to do POSIX pThread and all of that for some reason still won't compile. Can you make an EXE or search yourself for more of the biomes with in about 1k radius like you did for adventure time? But include Warm Ocean biome (Coral reefs for 1.13) Tried everything to get this to run

**Comment by Cubitect** [comment]
I updated the repository and tried to make it more cross-platform compatible. 
The finder I used to get those seeds was kinda hacky and I intend to replace the seed filters, rather than update them. I just uploaded a version that is still in development, which uses the new biome checkers. It should already work and outline the API though.

Here is what I currently get for 1.13 all-biome seeds between 0 and 10^10 (range = 1024):
```
1099513461
2383566779
2943461573
3241303026
3822918169
4144565466
5175189283
5724348410
```
Have a look at `find_compactbiomes.c` to find some seeds yourself and/or customise the biomes that you want to find.

I don't really have much time currently to properly search for more seed or polish up the finder, but hopefully this could help you.
