### ISSUE TITLE
search4QuadBases returns no seeds (in file) when using MONUMENT_CONFIG

### ISSUE THREAD

**Issue by Anunayj** [Cubitect/cubiomes#20]
I tried modifying the quad witch seed finder to find Quad monuments.
All I changed was `featureConfig = MONUMENT_CONFIG`
and the biomes from `swampland` to `deepocean`. but whenever  i run the program it returns nothing for Quad Monument seeds (I mean the search4QuadBases does return no seeds) in the file.

Probably me messing something up, could you help with that.
Sorry for bothering.

**Comment by Cubitect** [comment]
Indeed `isLargeStructureBase()` was broken, it should work now.
Note, that because of their size, quad-monuments will always have their corners outside the spawn radius of a single player. However, you can get pretty good seeds with about 92% inside range.

Large structure generation works rather different to other structures as they use a triangular probability distribution for their placement rather than uniform. This means that monuments tend to generate near the middle of their respective region. Good quad-monuments are therefore much much rarer than quad-witch-huts. The only quad-monument-seed-bases I have found are 
```
775379617447
97326727082256
``` 
and I checked over 3*10^13 of the 2^48 possible bases. If you do want to search for more quad-bases, it will probably take one or several weeks to get through all 2^48, depending on how beefy your computer is. 

I suggest just using one of the above seed-bases. You can move the quad-monument around using `moveStructure()`, and then check all 65536 high bit variations for valid biomes using `isViableOceanMonumentPos()`. Simply replacing `swampland` with `deepocean` won't work because large structures check for biomes in an area not just at a point. Also the swamp-hut finder code contains several optimisation filters specific to swamps which you need to remove.

Finally, I'm not sure about the practical usefulness of a quad-monument, because you can probably fill the mob cap with two just monuments.
