### ISSUE TITLE
Village generation biome list error

### ISSUE THREAD

**Issue by nnnik** [Cubitect/cubiomes#35]
Village generation is possible in Snowy Tundra in Minecraft Java Edition as of 1.14.
Yet the list in cubiomes states as:
`static const int villageBiomeList[] = {plains, desert, savanna, taiga};`
There does not seem to be a mechanism to switch to another biome list in the library.
Is this perhaps an oversight?

**Comment by nnnik** [comment]
See https://www.chunkbase.com/apps/village-finder#37436171902517249 for an example.

**Comment by Cubitect** [comment]
Thank you for reporting all these! I'm just going to reply for all three issues here. 

For the villages: I would like to keep support for older versions from 1.7 upwards, so this will actually need a separate biome list. 

For the monuments: I kept the biome generation for pre-1.13 because it is significantly faster than generating the ocean types, and the monument validation check only cares about the distinction between deep and normal oceans. However, I didn't consider that (warm and frozen) deep ocean near the shore can actually be converted to shallow oceans which is what has happens here.

The Outposts will indeed require a new check, which might get very expensive in order to test for viable village positions. I will have to look into that.

I'm actually in the middle of finishing a somewhat major update that deals mostly with performance optimisation in the layer generation. Given all this, it looks like I should rework the structure validation while I'm at it. I am thinking of bundling all the structure validators into a single function, and then deal with feature and version dependency in the background.

**Comment by nnnik** [comment]
Thanks for the reponse :)
Sadly we probably wont be able to wait for the new version to roll out.
Regarding the outpost checks I have written the code for 1.16 checks.
It is a new case which I assume wasnt considered in the library before.
Unlike all other structures so far the Outpost will fail to generate if there is an attempt at generating a village within 10 chunks of itself.
That means we can tell whether it generates or not by looking at the structure seed already.
I started to make an implementation at: https://github.com/End-Tech/cubiomes/tree/outpost-generation
Of course untested bt it should give you an idea what I mean and how I would approach this given the current structure of the code.
Source is https://github.com/KaptainWutax/FeatureUtils/blob/master/src/main/java/kaptainwutax/featureutils/structure/PillagerOutpost.java

**Comment by Cubitect** [comment]
Well, I've commited my changes, I haven't done all the testing that I would like, but things should be fixed now. It turns out the biome checks for structure generation has subtly changed as a whole in 1.16. Structures near the edge of biomes can now be in present or missing compared to 1.15. So the structure validation had to change anyway.

I haven't made a separate `getOupostPos()` yet, and instead have the checks in the biome validation, as prior to 1.16 the village check would also incorporate biomes. However, I might add a separate `getOutpostPos()` as a more performance friendly alternative.

**Comment by nnnik** [comment]
Hmm yeah - sadly we wont have the time to wait for another update :(
So we decided to switch libraries.
Feel free to use any code I/we created in the process of updating this library.
I now tested getOutpost and it works (ignoring the fact that it has a 1/5th chance of not generating based on the 48 bit seed even in 1.15)
