### ISSUE TITLE
Includes typo in finders.h

### ISSUE THREAD

**Issue by BoySanic** [Cubitect/cubiomes#45]
Hello!

I'm writing to you because I noticed that in finders.h, windows.h is typo'd as Windows.h, which causes a problem as it's case sensitive. 

`cubiomes/finders.h:11:10: fatal error: Windows.h: No such file or directory
   11 | #include <Windows.h>
      |`

I manually changed this in my copy of the file, but it seemed too minor of a change to be worth PRing it in. 

If you'd like me to PR that in, I can, but I figured it was minor enough that it can be resolved a lot quicker this way!

Thanks!

**Comment by Cubitect** [comment]
Thanks for the report.
I have only ever seen `windows.h` written with a capital `W` so I always assumed that you had to write it that way. As it turns out, you can usually use either version, because the NTFS file system on Windows ignores capitalisation. Presumably the lower case version would be the correct one in order to support cross compilation.
