### ISSUE TITLE
[BROKEN LINK] list of double-quad-huts within 32000 blocks see: ./seeds/alldoublequadhuts32k.txt

### ISSUE THREAD

**Issue by Delvin4519** [Cubitect/cubiomes#47]
I can't find the 1.12.2 double quad hut list of seeds. The link is broken

**Comment by Cubitect** [comment]
I removed all the seed lists while revising the definition of what a valid quad-hut even is. (I now try to categorize the quad-huts based more precisely on their relative positions, and how suitable they are for building a farm around them.) A seed list such as this should therefore be redone, not to mention updated for 1.13 and 1.16. The readme was rather outdated as a whole, since I was putting off updating it, because I wanted to write a proper intro for structure finding. That should be done now. However, the seed lists will still be missing for now, but if you really want to, you can find them in older commits like [here](https://github.com/Cubitect/cubiomes/tree/7dea686d31e7bc39623737e92754672429dddc2a/seeds).

**Comment by Cubitect** [comment]
I now have a repository [here](https://github.com/Cubitect/seed-lists) where I plan to keep seed list. It contains some updated lists for multi quad huts.
