### ISSUE TITLE
Is there a way to find mob spawner clusters from a seed?

### ISSUE THREAD

**Issue by mvrozanti** [Cubitect/cubiomes#54]
By mob spawner clusters I mean: mob spawners that are close enough to each other so that a point between them where all are simultaneously active (within 16-block distance of the point) exists.

I'm pretty sure cubiomes is capable of this, but I'm not sure where to start. My initial idea is to just keep generating chunks around a block, check for clusters using those chunks and print if there is, go to the next block and repeat but I'm kind of skeptical about the performance of this plan

**Comment by gsquaredxc** [comment]
I’m pretty sure spawners are on population. That means they are not consistent for the same seed and depend on direction of travel to said spawner.

**Comment by Badel2** [comment]
Correct, cubiomes can only find structures that do not depend on the 3D terrain because it's much faster this way, and spawners must always generate inside a "cave" so you could only get a list of possible spawner locations, and most of them will be wrong.

I recently made a tool to find spawner clusters but it only works if you pass it a pregenerated world, here:

https://badel2.github.io/slime_seed_finder/multi_spawner.html

If you have any questions or it doesn't work, open an issue in [my repo](https://github.com/badel2/slime_seed_finder) to avoid spamming here.

But I have a question, does anyone know the algorithm to find the intersection of more than 2 spheres? I'm just bruteforcing all the possible points and it is fast enough, but I couldn't find the proper way to do it. 2 spheres is easy, it's (s1+s2)/2, but 3 spheres is not the "center of mass", it's somewhere around the intersection of the first 2...

**Comment by mvrozanti** [comment]
I guess that's not an issue for cubiomes then. I'll close this. Thanks for the resources @Badel2 I'll definitely check it out

**Comment by mvrozanti** [comment]
>I’m pretty sure spawners are on population. That means they are not consistent for the same seed and depend on direction of travel to said spawner.
@gsquaredxc may I ask, where did you get this information from?

**Comment by mvrozanti** [comment]
@Badel2 you don't want only 2-spheres intersection, you want [N-spheres intersection](https://math.stackexchange.com/questions/562240/how-to-find-the-intersection-of-three-spheres-full-solutions), am I right?
