### ISSUE TITLE
Bedrock unsupported?

### ISSUE THREAD

**Issue by Ldalvik** [Cubitect/cubiomes#77]
Is there a specific reason Bedrock is unsupported? Structures only generate correctly for Java Edition.

**Comment by Cubitect** [comment]
Mimicking the Minecraft world generation requires very detailed knowledge of its internal workings and requires a lot of primary research. Just looking at the final worlds that the game generates is generally not enough and the necessary information can only really be obtained by writing custom mods that modify or debug core functions of the game. Bedrock does not support modding in this way. Addons, plugins, resource packs etc. are not a replacement, since that only gives you very limited access to parts of the game that Mojang has gracefully chosen to expose. 

Furthermore, I do not own Bedrock edition, so I can't be the one to develop or maintain support for it.

**Comment by Ldalvik** [comment]
Thanks for the answer :)

**Comment by Delvin4519** [comment]
Hello, I just wanted to mention that as of last summer, Mojang has made some changes to Bedrock edition that means all current Java players have a copy of Win10 Bedrock edition. There are programs, namely the one from Carjem's Bedrock Launcher Lite for Win10 that have saved all copiess of Win10 Bedrock edition back to 2016. 

Therefore, any Java MC player can access copies of any Bedrock Edition version back to 2016 on Win10. This means it is possible to for a Java MC player to compare worldgen results to a valid copy of Bedrock on PC.

I do agree that there aren't a lot of ways to debug Bedrock edition code, that one is still tricky, though.
